routes/admin.php
<?php

use App\Http\Controllers\admin\AdminController;
use App\Http\Controllers\Admin\AlbumController;
use App\Http\Controllers\Admin\ArtistController;
use App\Http\Controllers\Admin\SongController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/dashboard', function () {
    return view('admin.dashboard');
})->name('dashboard');
Route::post('/busquedaAlbun', [AdminController::class, 'buscar_albun'])->name('albums.busquedaAlbun');
Route::post('/busquedaArtista', [AdminController::class, 'busquedaArtista'])->name('artists.busquedaArtista');
Route::post('/busquedaCancion', [AdminController::class, 'busquedaCancion'])->name('songs.busquedaCancion');
Route::resource('/albums', AlbumController::class);
Route::resource('/artists', ArtistController::class);
Route::resource('/songs', SongController::class);

routes/web.php
<?php

use App\Http\Controllers\artist\ArtistController;
use App\Http\Controllers\User\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [UserController::class, 'index'])->name('home');
Route::post('Loginv2', [UserController::class, 'loginv2'])->name('loginv2');
Route::post('logoutv2', [UserController::class, 'logoutv2'])->name('logoutv2');

app/Models/Song.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Song extends Model
{
    use HasFactory;
    protected $fillable = ['name','album_id', 'artist_id'];
    public function artist()
    {
        return $this->belongsTo(Artist::class);
    }
    public function album()
    {
        return $this->belongsTo(Album::class);
    }
}

app/Http/Controllers/admin/SongController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Album;
use App\Models\Artist;
use App\Models\Song;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class SongController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $songs  = songs();
        if (isset($songs["message"])) {
            if ($songs["message"] == "token_expired") {
                generarToken();
                $songs = songs();
            } else {
                $songs = [];
            }
        }
        return view('admin.songs.index', compact('songs'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $artists = Artist::all()->toArray();
        $albums = Album::all()->toArray();
        return view('admin.songs.create', compact('artists', 'albums'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'album_id' =>  'required|exists:albums,id',
            'artist_id' => 'required|exists:artists,id',
        ]);
        $data = $request->all();
        Song::create($data);
        session()->flash('swal', [
            'icon' => 'success',
            'text' => 'Cancion  creada',
            'title' =>  '!Buen trabajo!'
        ]);
        return redirect()->route('songs.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $song = Song::where('id', $id)->first();
        $artists = Artist::all()->toArray();
        $albums = Album::all()->toArray();
        return view('admin.songs.edit', compact('song', 'artists', 'albums'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $request->validate([
            'name' => 'required',
            'album_id' =>  'required|exists:albums,id',
            'artist_id' => 'required|exists:artists,id',
        ]);
        $data = $request->all();
        $song = Song::find($id);
        $song->update($data);
        session()->flash('swal', [
            'icon' => 'success',
            'text' => 'Cancion  actualizada',
            'title' =>  '!Buen trabajo!'
        ]);
        return redirect()->route('songs.edit', $id);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $song = Song::find($id);
        $song->delete();
        session()->flash('swal', [
            'icon' => 'success',
            'text' => 'Cancion  eliminada',
            'title' =>  '!buem trabajo!'
        ]);
        return redirect()->route('songs.index');
    }
}

app/View/Components/AdminLayout.php
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class AdminLayout extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('layouts.admin');
    }
}

resources/views/admin/songs/create.blade.php
<x-admin-layout>
    @php
        $ruta = route('songs.store');
        if (substr($ruta, 0, strlen('http://localhost/')) == 'http://localhost/') {
            $ruta = str_replace('http://localhost/', 'http://127.0.0.1:8000/', $ruta);
        }
    @endphp
    <form action="{{  $ruta }}" method="post" class="bg-white rounded-lg p-6 shadow-lg">
        @csrf
        <x-validation-errors class="mb-4"></x-validation-errors>

        <div class="mb-4">
            <x-label class="mb-3">Nombre</x-label>
            <x-input class="w-full" value="{{ old('name') }}" name="name"
                placeholder="escriba el nombre de la cancion"></x-input>
        </div>
        <div class="mb-4">
            <x-label class="mb-1">Artista</x-label>
            <select class="tags-multiple" name="artist_id" style="width: 100%">
                <option value="">Selecina un artista</option>
                @foreach ($artists as $artist)
                    <option value="{{ $artist['id'] }}"@selected(old('artist_id') == $artist['id'])>{{ $artist['name'] }}</option>
                @endforeach
            </select>

        </div>
        <div class="mb-4">
            <x-label class="mb-1">Album</x-label>
            <select class="tags-multiple" name="album_id" style="width: 100%">
                <option value="">Selecina un album</option>
                @foreach ($albums as $album)
                    <option value="{{ $album['id'] }}"@selected(old('album_id') == $album['id'])>{{ $album['name'] }}</option>
                @endforeach
            </select>

        </div>
        <div>
            <x-button class="flex justify-end">
                Crear artista
            </x-button>
        </div>
    </form>

    @push('js')
        <script>
            $(document).ready(function() {
                $('.tags-multiple').select2();
            });
        </script>
    @endpush
</x-admin-layout>

resources/views/admin/songs/edit.blade.php
<x-admin-layout>
    @php
        $ruta = route('songs.update', $song['id']);
        if (substr($ruta, 0, strlen('http://localhost/')) == 'http://localhost/') {
            $ruta = str_replace('http://localhost/', 'http://127.0.0.1:8000/', $ruta);
        }
    @endphp
    <form action="{{ $ruta }}" method="post" class="bg-white rounded-lg p-6 shadow-lg">
        @csrf
        @method('PUT')
        <x-validation-errors class="mb-4"></x-validation-errors>
        <div class="mb-4">
            <x-label class="mb-3">Nombre</x-label>
            <x-input class="w-full" value="{{ old('name', $song->name) }}" name="name"
                placeholder="escriba el nombre de la cancion"></x-input>
        </div>
        <div class="mb-4">
            <x-label class="mb-1">Artista</x-label>
            <select class="tags-multiple" name="artist_id" style="width: 100%">
                <option value="">Selecina un artista</option>
                @foreach ($artists as $artist)
                    <option value="{{ $artist['id'] }}"@selected(old('artist_id', $song['artist_id']) == $artist['id'])>{{ $artist['name'] }}</option>
                @endforeach
            </select>

        </div>
        <div class="mb-4">
            <x-label class="mb-1">Album</x-label>
            <select class="tags-multiple" name="album_id" style="width: 100%">
                <option value="">Selecina un album</option>
                @foreach ($albums as $album)
                    <option value="{{ $album['id'] }}"@selected(old('album_id', $song['album_id']) == $album['id'])>{{ $album['name'] }}</option>
                @endforeach
            </select>

        </div>
        <div>
            <x-danger-button class="mr-2" onclick="deleteCategory()">Eliminar</x-danger-button>
            <x-button class="flex
                        justify-end">
                Actualizar cancion
            </x-button>
        </div>
    </form>
    @php
        $rutadelete = route('songs.destroy', $song['id']);
        if (substr($rutadelete, 0, strlen('http://localhost/')) == 'http://localhost/') {
            $rutadelete = str_replace('http://localhost/', 'http://127.0.0.1:8000/', $rutadelete);
        }
    @endphp
    <form id="formDelete" action="{{ $rutadelete }}" method="post">
        @csrf
        @method('DELETE')
    </form>
    @push('js')
        <script>
            $(document).ready(function() {
                $('.tags-multiple').select2();
            });

            function deleteCategory() {
                let form = document.getElementById('formDelete');
                form.submit();
            }
        </script>
    @endpush
</x-admin-layout>

resources/views/admin/songs/index.blade.php
<x-admin-layout>
    <div class="flex justify-end mb-4">
        @php
            $rutacreate = route('songs.create');
            if (substr($rutacreate, 0, strlen('http://localhost/')) == 'http://localhost/') {
                $rutacreate = str_replace('http://localhost/', 'http://127.0.0.1:8000/', $rutacreate);
            }
        @endphp
        <a class="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700"
            href="{{ $rutacreate }}">Nuevo cancion</a>
    </div>
    <div class="mb-4">
        @php
            $rutabuscar = route('songs.busquedaCancion');
            if (substr($rutabuscar, 0, strlen('http://localhost/')) == 'http://localhost/') {
                $rutabuscar = str_replace('http://localhost/', 'http://127.0.0.1:8000/', $rutabuscar);
            }
        @endphp
        <form method="POST" action="{{ $rutabuscar }}">
            @csrf
            <x-label class="mb-2">Artistas</x-label>
            <x-input name="descipcion" style="width: 80%"></x-input>
            <button type="submit"
                class="text-white right-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Buscar</button>
        </form>
    </div>
    <ul class="space-y-8">
        <strong>Lista de canciones</strong>
        @if (count($songs) == 0)
            <div class="flex items-center p-4 mb-4 text-sm text-yellow-800 border border-yellow-300 rounded-lg bg-yellow-50 dark:bg-gray-800 dark:text-yellow-300 dark:border-yellow-800"
                role="alert">
                <svg class="flex-shrink-0 inline w-4 h-4 mr-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                    fill="currentColor" viewBox="0 0 20 20">
                    <path
                        d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z" />
                </svg>
                <span class="sr-only">Info</span>
                <div>
                    <span class="font-medium">No se encontraron resultados</span> intente nuevamente.
                </div>
            </div>
        @else
            <div class="flex items-center p-4 mb-4 text-sm text-green-800 border border-green-300 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400 dark:border-green-800"
                role="alert">
                <svg class="flex-shrink-0 inline w-4 h-4 mr-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                    fill="currentColor" viewBox="0 0 20 20">
                    <path
                        d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z" />
                </svg>
                <span class="sr-only">Info</span>
                <div>
                    <span class="font-medium">se encontraton </span>{{ count($songs) }} resultados.
                </div>
            </div>
            @foreach ($songs as $song)
                <li class="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div>
                        <strong>Artista: {{ $song['artist'] }}</strong>
                        <img class="aspect-[16/9] object-cover object-center w-full" src="{{ $song['image'] }}"
                            alt="">

                    </div>
                    <div>
                        <strong>Album: {{ $song['album'] }}</strong>
                    </div>
                    <div>
                        <h1 class="text-xl font-semibold">{{ $song['name'] }}</h1>

                        <hr class="mt-1 mb-2">
                        <div class="flex  mt-4">
                            @php
                                $rutaedit = route('songs.edit', $song['id']);
                                if (substr($rutaedit, 0, strlen('http://localhost/')) == 'http://localhost/') {
                                    $rutaedit = str_replace('http://localhost/', 'http://127.0.0.1:8000/', $rutaedit);
                                }
                            @endphp
                            <a href="{{ $rutaedit }}"
                                class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
                                Editar</a>
                        </div>
                    </div>
                </li>
            @endforeach
        @endif

    </ul>

    @push('js')
        <script>
            $(document).ready(function() {
                $('.tags-multiple').select2();
            });
        </script>
    @endpush
</x-admin-layout>

resources/views/admin/songs/show.blade.php
<x-admin-layout>
    <strong class="flex justify-center">Artista: {{ $artist['name'] }}</strong>
    <div class="mb-2">
        <img class="aspect-[10/3] object-cover object-center w-full" src="{{ $artist['image'] }}" alt="">
    </div>

    <div class="mt-4">

        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
            <strong class="my-3"> Lista de canciones</strong>
            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-3">
                            Artista
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Genero
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Album
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Cancion
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($artist->songs as $item)
                        <tr
                            class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">

                            <th scope="row"
                                class="flex items-center px-6 py-4 text-gray-900 whitespace-nowrap dark:text-white">
                                <img class="w-10 h-10 rounded-full" src="{{ $artist->image }}" alt="Jese image">
                                <div class="pl-3">
                                    <div class="text-base font-semibold">{{ $artist->name }}</div>
                                </div>
                            </th>
                            <th class="px-6 py-4">
                                @empty($artist->gender->name)
                                    No tiene genero
                                @else
                                    {{ $artist->gender->name }}
                                @endempty
                            </th>
                            <th class="px-6 py-4">
                                {{ $item->album->name }}
                            </th>
                            <td class="px-6 py-4">
                                <div class="flex items-center">
                                    <div class="h-2.5 w-2.5 rounded-full bg-green-500 mr-2"></div> {{ $item->name }}
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

    </div>
</x-admin-layout>